apps:
  frontend:
    - public/
    - src:
      - components/
      - features/
      - hooks/
      - pages/
      - libs/
      - locales/
      - models/
      - styles/
      - templates/
      - types/
      - utils/
      - index.tsx
    - assets:
      - css/
      - fonts/
      - vid/
      - img:
        - svg/
        - icon/
    - vite.config.ts
    - tsconfig.app.json
    - tailwind.config.ts
    - components.json
    - package.json

  backend:
    - api:
      - handlers/
      - integrations/
      - utils/
    - src/
    - lib/
    - routes/
    - types/
    - package.json

assets:    # Global assets shared across multiple apps
  - css/
  - fonts/
  - vid/
  - img/

infra:
  cloudflare:
    - terraform:
      - main.tf
      - variables.tf
      - outputs.tf
    - workers:
      - src:
        - index.ts
      - wrangler.json
      - wrangler.config.mts
      - worker-configuration.d.ts
  supabase:
    - functions/
    - db:
      - migrations/
      - seeds/

packages:
  - ui/
  - hooks/
  - utils/

db:
  - migrations/
  - seeds/
  - models/Schema.ts
  - drizzle.config.ts

docs:
  - en/
  - ja/
  - ko/
  - zh/

automation: scripts/

.github:
  - workflows/
  - prompts/
  - instructions/

tests:
  - unit:
    - vitest.config.mts
    - vitest-setup.ts
  - e2e:
    - playwright.config.ts
    - playwright-setup.ts
  - integration:
    - pactum.config.ts
  - package.json

releases:

config_files:
  - package.json # Global configuration
  - tsconfig.json
  - tsconfig.node.json
  - deno.json
  - deno.lock
  - README.md